# Generated by Django 5.2.7 on 2025-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pack_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('ownership', models.CharField(max_length=200)),
                ('uploaded_on', models.DateField()),
                ('pack_name', models.CharField(max_length=50)),
                ('last_modification', models.DateField()),
                ('pack_status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], max_length=20)),
                ('tags', models.CharField(max_length=300, null=True)),
                ('pack_delivery', models.CharField(choices=[('Direct', 'Direct'), ('Guardian', 'Guardian'), ('Public', 'Public')], max_length=20)),
                ('pack_type', models.CharField(choices=[('Event-Based', 'Event-Based'), ('Location-Based', 'Location-Based'), ('Countdown', 'Countdown')], max_length=30)),
                ('total_files', models.IntegerField(default=0)),
                ('has_expiry', models.BooleanField(default=False)),
                ('expiry_at', models.DateField(null=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
                'ordering': ['-uploaded_on'],
                'managed': False,
            },
        ),
    ]
