# Generated by Django 6.0 on 2025-12-12 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageExplorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_nickname', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('posted_at', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
            options={
                'db_table': 'pack_explorar',
                'ordering': ['-posted_at'],
            },
        ),
    ]
