# Generated by Django 6.0 on 2025-12-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('receiver_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('visitor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(max_length=150)),
                ('notification_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('Push', 'Push'), ('In App', 'In App'), ('SMS', 'SMS'), ('System', 'System'), ('Unlock', 'Unlock')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Low', '🟢 Low'), ('Medium', '"🟠 Medium'), ('High', '🔴 High'), ('Critical', '🔴🔴🔴 Critical')], default='Medium', max_length=30)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.log')),
                ('receiver_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification_Receivers', to='contenttypes.contenttype')),
                ('sender_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification_Senders', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'notification_center',
                'ordering': ['-created_at'],
            },
        ),
    ]
