# Generated by Django 5.2.7 on 2025-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_type', models.CharField(choices=[('Guardian', 'Guardian'), ('User', 'User'), ('Beneficiary', 'Beneficiary')], max_length=50)),
                ('visitor_id', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('log_action', models.CharField(choices=[('LOGIN_SUCCESS', 'User login success'), ('LOGIN_FAILED', 'User login failed'), ('LOGOUT', 'User logged out'), ('ACCOUNT_CREATED', 'New account created'), ('ACCOUNT_VERIFIED', 'User verified email'), ('ACCOUNT_UPDATED', 'User updated profile'), ('PASSWORD_CHANGED', 'Password updated'), ('PACKAGE_CREATED', 'New package created'), ('PACKAGE_UPDATED', 'Package modified'), ('PACKAGE_DELETED', 'Package deleted'), ('PACKAGE_UNLOCKED', 'Package unlocked'), ('GUARDIAN_ASSIGNED', 'Guardian assigned'), ('GUARDIAN_REMOVED', 'Guardian removed'), ('BENEFICIARY_CONNECTED', 'Beneficiary connected'), ('BENEFICIARY_UPDATED', 'Beneficiary profile updated'), ('COMMUNICATION_SENT', 'Communication sent'), ('COMMUNICATION_UPDATED', 'Communication updated'), ('SYSTEM_EVENT', 'System generated log')], max_length=100)),
                ('log_at', models.DateTimeField(auto_now_add=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('log_stat', models.CharField(default='Successful !', max_length=30)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
