# Generated by Django 6.0 on 2025-12-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credenntials',
            fields=[
                ('credential_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password_hashed', models.TextField()),
                ('password_salt', models.TextField()),
                ('security_qu1', models.CharField(max_length=200)),
                ('security_qu2', models.CharField(max_length=200)),
                ('security_ans1', models.CharField(max_length=200)),
                ('security_ans2', models.CharField(max_length=200)),
                ('recover_email', models.CharField(max_length=100, unique=True)),
                ('two_factor', models.BooleanField(default=False)),
                ('two_factor_token', models.TextField(blank=True, null=True)),
                ('password_change', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('failed_entry', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.log')),
            ],
        ),
    ]
