# Generated by Django 5.2.7 on 2025-11-23 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0003_guardian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='communicationMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_email', models.EmailField(max_length=100, unique=True)),
                ('relationship', models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('GRANDMOTHER', 'GRANDMOTHER'), ('GRANDFATHER', 'GRANDFATHER'), ('STEP FATHER', 'STEP FATHER'), ('STEP MOTHER', 'STEP MOTHER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('COUNIN', 'COUSIN'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE'), ('FAMILY FRIEND', 'FAMILY FRIEND'), ('NEIGHBOR', 'NEIGHBOR'), ('MENTOR', 'MENTOR'), ('SOCIAL WORKER', 'SOCIAL WORKER'), ('OTHER', 'OTHER'), ('LEGEAL GUARDIAN', 'LEGEAL GUARDIAN'), ('FOSTER PARENT', 'FOSTER PARENT'), ('CARETAKER', 'CARETAKER')], max_length=50)),
                ('com_m1', models.CharField(max_length=300)),
                ('com_m2', models.CharField(blank=True, max_length=300, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('b_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.beneficiary')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
