# Generated by Django 6.0 on 2025-12-12 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('user_registration', '0004_user_active_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisedPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packat', models.CharField(choices=[('LOCKED', 'Locked Supervision'), ('Timed', 'Timed Unlock'), ('Manual', 'Guardian Manual Unlock')], max_length=50)),
                ('guadian_control', models.BooleanField(default=True)),
                ('guardian_revealing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard_stat', models.CharField(choices=[('Pending', 'Waiting for Guardian Sign up'), ('Active', 'Active Guardian')], max_length=20)),
                ('user_stat', models.CharField(choices=[('Active', 'Active'), ('Departed', 'Passed Away')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.beneficiary')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.guardian')),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervised_packs',
            },
        ),
    ]
