# Generated by Django 5.2.7 on 2025-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('milestone_id', models.AutoField(primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=100)),
                ('ben_id', models.IntegerField()),
                ('ben_full_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verified_documents', models.BooleanField(default=False)),
                ('match_pack', models.BooleanField(default=False)),
                ('family_name', models.CharField(max_length=100)),
                ('file_format', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user_reference_files', models.TextField(blank=True, null=True)),
                ('beneficiary_files', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'milestone_upload',
            },
        ),
    ]
