# Generated by Django 6.0 on 2025-12-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=200, null=True)),
                ('login_start', models.DateTimeField(auto_now_add=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('successful_log', models.BooleanField(default=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.log')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-login_start'],
            },
        ),
    ]
