# Generated by Django 5.2.7 on 2025-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_full_name', models.CharField(max_length=255)),
                ('b_email', models.EmailField(max_length=254)),
                ('b_username', models.CharField(max_length=255)),
            ],
        ),
    ]
