# Generated by Django 5.2.7 on 2025-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_full_name', models.CharField(max_length=255)),
                ('g_email', models.EmailField(max_length=254)),
                ('g_username', models.CharField(max_length=255)),
            ],
        ),
    ]
