# Generated by Django 6.0 on 2025-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('USER', 'User'), ('BENEFICIARY', 'Beneficiary'), ('GUARDIAN', 'Guardian')], default='USER', max_length=20),
        ),
    ]
